name: flutter_clean_skeleton
description: "A flutter project with clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  http: ^1.2.1
  sqflite: ^2.3.3+1
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg